name: build-qrcode-project
run-name: Build QRCode project

on: [push,workflow_dispatch]

env:
  ARTIFACT_VERSION: 0.0.7

jobs:
  build-comparator-app:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: chmod u+x gradlew
      - run: ./gradlew -PARTIFACT_VERSION=$ARTIFACT_VERSION distribute
      - run: |
             sonar-scanner \
             -Dsonar.projectKey=goa.systems.qrcode \
             -Dsonar.sources=src/main/java \
             -Dsonar.java.binaries=build/classes \
             -Dsonar.host.url=http://localhost:9000 \
             -Dsonar.login=sqp_c6817dbf9cee87698737f555fb3f461179321836
      - run: |
             scp build/distributions/goa.systems.qrcode-$ARTIFACT_VERSION.tar.gz foo@tools.goa.systems:/tmp
             ssh foo@tools.goa.systems "deploymaven /tmp/goa.systems.qrcode-$ARTIFACT_VERSION.tar.gz goa.systems commons $ARTIFACT_VERSION"
             ssh foo@tools.goa.systems "rm /tmp/goa.systems.qrcode-$ARTIFACT_VERSION.tar.gz"